import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    // Navbar
    home: "Home",
    friends: "Friends",
    map: "Map",
    weatherGPT: "WeatherGPT",
    alerts: "Alerts",
    agriculture: "Agriculture",
    railway: "Railway",
    settings: "Settings",
    
    // Home
    greeting_morning: "Good Morning",
    greeting_afternoon: "Good Afternoon",
    greeting_evening: "Good Evening",
    welcomeBack: "Welcome back",
    todaysWeather: "Today's Weather",
    feelsLike: "Feels Like",
    humidity: "Humidity",
    windSpeed: "Wind Speed",
    uvIndex: "UV Index",
    rainfall: "Rainfall",
    hourlyForecast: "Hourly Forecast",
    weeklyForecast: "Weekly Forecast",
    weatherAlerts: "Weather Alerts",
    noAlerts: "No alerts right now",
    quickActions: "Quick Actions",
    checkWeather: "Check Weather",
    talkToAI: "Talk to AI",
    viewMap: "View Map",
    friendsWeather: "Friends Weather",
    viewAll: "View All",
    sun: "Sun",
    mon: "Mon",
    tue: "Tue",
    wed: "Wed",
    thu: "Thu",
    fri: "Fri",
    sat: "Sat",
    today: "Today",
    tomorrow: "Tomorrow",
    goodMorning: "Good Morning",
    sunny: "Sunny",
    cloudy: "Cloudy",
    rainy: "Rainy",
    windy: "Windy",
    stormy: "Stormy",
    clear: "Clear",
    partlyCloudy: "Partly Cloudy",
    
    // Settings
    language: "Language",
    selectLanguage: "Select Language",
    english: "English",
    hindi: "हिंदी",
    marathi: "मराठी",
    tamil: "தமிழ்",
    telugu: "తెలుగు",
    bengali: "বাংলা",
  },
  hi: {
    // Navbar
    home: "होम",
    friends: "मित्र",
    map: "नक्शा",
    weatherGPT: "वेदरजीपीटी",
    alerts: "चेतावनी",
    agriculture: "कृषि",
    railway: "रेलवे",
    settings: "सेटिंग्स",
    
    // Home
    greeting_morning: "सुप्रभात",
    greeting_afternoon: "शुभ दोपहर",
    greeting_evening: "शुभ संध्या",
    welcomeBack: "वापसी पर स्वागत",
    todaysWeather: "आज का मौसम",
    feelsLike: "महसूस होता है",
    humidity: "नमी",
    windSpeed: "हवा की गति",
    uvIndex: "यूवी इंडेक्स",
    rainfall: "बारिश",
    hourlyForecast: "घंटेवार पूर्वानुमान",
    weeklyForecast: "साप्ताहिक पूर्वानुमान",
    weatherAlerts: "मौसम चेतावनी",
    noAlerts: "अभी कोई चेतावनी नहीं",
    quickActions: "त्वरित कार्य",
    checkWeather: "मौसम देखें",
    talkToAI: "AI से बात करें",
    viewMap: "नक्शा देखें",
    friendsWeather: "मित्रों का मौसम",
    viewAll: "सभी देखें",
    sun: "रवि",
    mon: "सोम",
    tue: "मंगल",
    wed: "बुध",
    thu: "गुरु",
    fri: "शुक्र",
    sat: "शनि",
    today: "आज",
    tomorrow: "कल",
    goodMorning: "सुप्रभात",
    sunny: "धूप",
    cloudy: "बादल",
    rainy: "बारिश",
    windy: "हवा",
    stormy: "तूफान",
    clear: "साफ",
    partlyCloudy: "कुछ बादल",
    
    // Settings
    language: "भाषा",
    selectLanguage: "भाषा चुनें",
    english: "English",
    hindi: "हिंदी",
    marathi: "मराठी",
    tamil: "தமிழ்",
    telugu: "తెలుగు",
    bengali: "বাংলা",
  },
  mr: {
    home: "मुख्यपृष्ठ",
    friends: "मित्र",
    map: "नकाशा",
    weatherGPT: "वेदरजीपीटी",
    alerts: "सूचना",
    agriculture: "शेती",
    railway: "रेल्वे",
    settings: "सेटिंग्ज",
    greeting_morning: "सुप्रभात",
    greeting_afternoon: "शुभ दुपार",
    greeting_evening: "शुभ संध्याकाळ",
    welcomeBack: "पुन्हा स्वागत",
    todaysWeather: "आजचे हवामान",
    feelsLike: "जाणवते",
    humidity: "आर्द्रता",
    windSpeed: "वाऱ्याचा वेग",
    uvIndex: "यूव्ही इंडेक्स",
    rainfall: "पाऊस",
    hourlyForecast: "तासानुसार अंदाज",
    weeklyForecast: "साप्ताहिक अंदाज",
    weatherAlerts: "हवामान सूचना",
    noAlerts: "सध्या कोणतीही सूचना नाही",
    quickActions: "त्वरित क्रिया",
    checkWeather: "हवामान पहा",
    talkToAI: "AI शी बोला",
    viewMap: "नकाशा पहा",
    friendsWeather: "मित्रांचे हवामान",
    viewAll: "सर्व पहा",
    sun: "रवि",
    mon: "सोम",
    tue: "मंगळ",
    wed: "बुध",
    thu: "गुरु",
    fri: "शुक्र",
    sat: "शनि",
    today: "आज",
    tomorrow: "उद्या",
    goodMorning: "सुप्रभात",
    sunny: "ऊन",
    cloudy: "ढगाळ",
    rainy: "पाऊस",
    windy: "वारा",
    stormy: "वादळ",
    clear: "स्वच्छ",
    partlyCloudy: "अंशतः ढगाळ",
    language: "भाषा",
    selectLanguage: "भाषा निवडा",
    english: "English",
    hindi: "हिंदी",
    marathi: "मराठी",
    tamil: "தமிழ்",
    telugu: "తెలుగు",
    bengali: "বাংলা",
  },
  ta: {
    home: "முகப்பு",
    friends: "நண்பர்கள்",
    map: "வரைபடம்",
    weatherGPT: "வெதர்ஜிபிடி",
    alerts: "எச்சரிக்கைகள்",
    agriculture: "விவசாயம்",
    railway: "ரயில்வே",
    settings: "அமைப்புகள்",
    greeting_morning: "காலை வணக்கம்",
    greeting_afternoon: "மதிய வணக்கம்",
    greeting_evening: "மாலை வணக்கம்",
    welcomeBack: "மீண்டும் வருக",
    todaysWeather: "இன்றைய வானிலை",
    feelsLike: "உணரப்படுகிறது",
    humidity: "ஈரப்பதம்",
    windSpeed: "காற்றின் வேகம்",
    uvIndex: "UV குறியீடு",
    rainfall: "மழை",
    hourlyForecast: "மணிநேர முன்னறிவிப்பு",
    weeklyForecast: "வாராந்திர முன்னறிவிப்பு",
    weatherAlerts: "வானிலை எச்சரிக்கைகள்",
    noAlerts: "இப்போது எச்சரிக்கைகள் இல்லை",
    quickActions: "விரைவு செயல்கள்",
    checkWeather: "வானிலை பார்க்க",
    talkToAI: "AI உடன் பேசு",
    viewMap: "வரைபடம் பார்",
    friendsWeather: "நண்பர்கள் வானிலை",
    viewAll: "அனைத்தையும் பார்",
    sun: "ஞாயிறு",
    mon: "திங்கள்",
    tue: "செவ்வாய்",
    wed: "புதன்",
    thu: "வியாழன்",
    fri: "வெள்ளி",
    sat: "சனி",
    today: "இன்று",
    tomorrow: "நாளை",
    goodMorning: "காலை வணக்கம்",
    sunny: "வெயில்",
    cloudy: "மேகமூட்டம்",
    rainy: "மழை",
    windy: "காற்று",
    stormy: "புயல்",
    clear: "தெளிவு",
    partlyCloudy: "பகுதி மேகமூட்டம்",
    language: "மொழி",
    selectLanguage: "மொழியை தேர்வு செய்",
    english: "English",
    hindi: "हिंदी",
    marathi: "मराठी",
    tamil: "தமிழ்",
    telugu: "తెలుగు",
    bengali: "বাংলা",
  },
  te: {
    home: "హోమ్",
    friends: "స్నేహితులు",
    map: "మ్యాప్",
    weatherGPT: "వెదర్జిపిటి",
    alerts: "హెచ్చరికలు",
    agriculture: "వ్యవసాయం",
    railway: "రైల్వే",
    settings: "సెట్టింగ్‌లు",
    greeting_morning: "శుభోదయం",
    greeting_afternoon: "శుభ మధ్యాహ్నం",
    greeting_evening: "శుభ సాయంత్రం",
    welcomeBack: "తిరిగి స్వాగతం",
    todaysWeather: "నేటి వాతావరణం",
    feelsLike: "అనిపిస్తుంది",
    humidity: "తేమ",
    windSpeed: "గాలి వేగం",
    uvIndex: "UV సూచిక",
    rainfall: "వర్షం",
    hourlyForecast: "గంటవారీ సూచన",
    weeklyForecast: "వారపు సూచన",
    weatherAlerts: "వాతావరణ హెచ్చరికలు",
    noAlerts: "ఇప్పుడు హెచ్చరికలు లేవు",
    quickActions: "త్వరిత చర్యలు",
    checkWeather: "వాతావరణం చూడండి",
    talkToAI: "AI తో మాట్లాడండి",
    viewMap: "మ్యాప్ చూడండి",
    friendsWeather: "స్నేహితుల వాతావరణం",
    viewAll: "అన్నీ చూడండి",
    sun: "ఆది",
    mon: "సోమ",
    tue: "మంగళ",
    wed: "బుధ",
    thu: "గురు",
    fri: "శుక్ర",
    sat: "శని",
    today: "నేడు",
    tomorrow: "రేపు",
    goodMorning: "శుభోదయం",
    sunny: "ఎండ",
    cloudy: "మేఘావృతం",
    rainy: "వర్షం",
    windy: "గాలి",
    stormy: "తుఫాను",
    clear: "స్పష్టం",
    partlyCloudy: "పాక్షికంగా మేఘావృతం",
    language: "భాష",
    selectLanguage: "భాషను ఎంచుకోండి",
    english: "English",
    hindi: "हिंदी",
    marathi: "मराठी",
    tamil: "தமிழ்",
    telugu: "తెలుగు",
    bengali: "বাংলা",
  },
  bn: {
    home: "হোম",
    friends: "বন্ধুরা",
    map: "মানচিত্র",
    weatherGPT: "ওয়েদারজিপিটি",
    alerts: "সতর্কতা",
    agriculture: "কৃষি",
    railway: "রেলওয়ে",
    settings: "সেটিংস",
    greeting_morning: "সুপ্রভাত",
    greeting_afternoon: "শুভ অপরাহ্ন",
    greeting_evening: "শুভ সন্ধ্যা",
    welcomeBack: "স্বাগতম",
    todaysWeather: "আজকের আবহাওয়া",
    feelsLike: "অনুভূত হয়",
    humidity: "আর্দ্রতা",
    windSpeed: "বাতাসের গতি",
    uvIndex: "UV সূচক",
    rainfall: "বৃষ্টি",
    hourlyForecast: "ঘণ্টাভিত্তিক পূর্বাভাস",
    weeklyForecast: "সাপ্তাহিক পূর্বাভাস",
    weatherAlerts: "আবহাওয়া সতর্কতা",
    noAlerts: "এখন কোনো সতর্কতা নেই",
    quickActions: "দ্রুত কাজ",
    checkWeather: "আবহাওয়া দেখুন",
    talkToAI: "AI এর সাথে কথা বলুন",
    viewMap: "মানচিত্র দেখুন",
    friendsWeather: "বন্ধুদের আবহাওয়া",
    viewAll: "সব দেখুন",
    sun: "রবি",
    mon: "সোম",
    tue: "মঙ্গল",
    wed: "বুধ",
    thu: "বৃহস্পতি",
    fri: "শুক্র",
    sat: "শনি",
    today: "আজ",
    tomorrow: "আগামীকাল",
    goodMorning: "সুপ্রভাত",
    sunny: "রোদ",
    cloudy: "মেঘলা",
    rainy: "বৃষ্টি",
    windy: "বাতাস",
    stormy: "ঝড়",
    clear: "পরিষ্কার",
    partlyCloudy: "আংশিক মেঘলা",
    language: "ভাষা",
    selectLanguage: "ভাষা নির্বাচন করুন",
    english: "English",
    hindi: "हिंदी",
    marathi: "मराठी",
    tamil: "தமிழ்",
    telugu: "తెలుగు",
    bengali: "বাংলা",
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(
    localStorage.getItem('language') || 'en'
  );

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = translations[language] || translations.en;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};